name: Worlds
main: surva\worlds\Worlds
version: 2.0.1
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11]
commands:
  worlds:
    description: "Worlds"
    usage: "/worlds list\n/worlds create <worldname> [type]\n/worlds <remove|load|unload|tp> <worldname>\n/worlds <copy|rename> <from> <to>\n/worlds set\n/worlds set permission <permissionstring>\n/worlds set gamemode <survival|creative|adventure|spectator>\n/worlds set <build|pvp|damage|drop|hunger|fly> <true|false>\n/worlds unset <permission|gamemode|build|pvp|damage|drop|hunger|fly>"
    aliases: ["ws"]
permissions:
  worlds.list:
    description: "List worlds"
    default: true
  worlds.admin:
    description: "Create worlds, delete worlds, set parameters, ..."
    default: op
    children:
      worlds.admin.create:
        description: "Create worlds"
        default: op
      worlds.admin.remove:
        description: "Remove worlds"
        default: op
      worlds.admin.copy:
        description: "Copy worlds"
        default: op
      worlds.admin.rename:
        description: "Rename worlds"
        default: op
      worlds.admin.load:
        description: "Load worlds"
        default: op
      worlds.admin.unload:
        description: "Unload worlds"
        default: op
      worlds.admin.teleport:
        description: "Teleport to worlds"
        default: op
      worlds.admin.set:
        description: "Set parameters"
        default: op
      worlds.admin.unset:
        description: "Unset parameters"
        default: op
      worlds.admin.build:
        description: "Allow building in protected worlds"
        default: op
      worlds.admin.interact:
        description: "Allow interacting in protected worlds"
        default: op
      worlds.admin.gamemode:
        description: "Don't change gamemode to world's gamemode"
        default: false
      worlds.admin.fly:
        description: "Fly in every world"
        default: false
